### ISSUE TITLE
Unit test failure

### ISSUE THREAD

**Issue by avalentino** [pytroll/pyorbital#8]
Running the test suite on Debian (sid amd64) gives the following error:

```
  ======================================================================
  FAIL: test_sunangles (pyorbital.tests.test_astronomy.TestAstronomy)
  Test the sun-angle calculations:
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/lamby/temp/cdt.20160208085132.sRBTiAzuyQ/pyorbital-0.3.2/pyorbital/tests/test_astronomy.py", line 53, in test_sunangles
      self.assertEqual(sun_theta, 60.371433482557833)
  AssertionError: 60.371433482573323 != 60.37143348255783
  
  ----------------------------------------------------------------------
  Ran 16 tests in 0.049s
  
  FAILED (failures=1)
```

See also [1] for more details

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=814071

**Comment by mraspaud** [comment]
Not directly a solution for the bug, but version 1.0.0 was released in august, maybe it would be preferable to package this version instead ? 
Hmmm, I see now only pypi has the release, sorry about that! It's now on github too :)

**Comment by avalentino** [comment]
Thanks @mraspaud,
I was not aware of the new release indeed.

Anyway the problem still persists with the new version:

```
======================================================================
FAIL: test_sunangles (pyorbital.tests.test_astronomy.TestAstronomy)
Test the sun-angle calculations:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pyorbital-1.0.0/pyorbital/tests/test_astronomy.py", line 53, in test_sunangles
    self.assertEqual(sun_theta, 60.371433482557833)
AssertionError: 60.371433482573323 != 60.37143348255783

----------------------------------------------------------------------
Ran 16 tests in 0.069s
```

Do you think that using 

```
self.assertAlmostEqual(sun_theta, 60.371433482557833)
```

instead of 

```
self.assertEqual(sun_theta, 60.371433482557833)
```

makes sense?

**Comment by storpipfugl** [comment]
It is a very aggressive test. The error is in the order of 1e-12 compared to IEEE 754 double precision epsilon being in the order of 1e-16 and machine implementation of  transcendental functions not being standardized. For these kind of tests it makes sense to drop the accuracy level to single precision tolerance in the order of  1e-8

**Comment by mraspaud** [comment]
@avalentino , @storpipfugl you are absolutely right, the test is too strict, so assertAlmostEqual should be used. Does the test pass then ? If it does, I'll update the package.

**Comment by avalentino** [comment]
The following patch seems to work

```
From: Antonio Valentino <antonio.valentino@tiscali.it>
Date: Tue, 16 Feb 2016 20:58:08 +0100
Subject: relax astronomy test condition

---
 pyorbital/tests/test_astronomy.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/pyorbital/tests/test_astronomy.py b/pyorbital/tests/test_astronomy.py
index ae39d1c..6666898 100644
--- a/pyorbital/tests/test_astronomy.py
+++ b/pyorbital/tests/test_astronomy.py
@@ -50,9 +50,9 @@ class TestAstronomy(unittest.TestCase):
         time_slot = datetime(2011, 9, 23, 12, 0)
         
         sun_theta = astr.sun_zenith_angle(time_slot, lon, lat)
-        self.assertEqual(sun_theta, 60.371433482557833)
+        self.assertAlmostEqual(sun_theta, 60.371433482557833, places=8)
         sun_theta = astr.sun_zenith_angle(time_slot, 0., 0.)
-        self.assertEqual(sun_theta, 1.8751916863323426)
+        self.assertAlmostEqual(sun_theta, 1.8751916863323426, places=8)
 
 def suite():
     """The suite for test_astronomy
```

**Comment by mraspaud** [comment]
@avalentino Version 1.0.1 is released now. Can you confirm it works, and close the issue ?

Thanks for the help ! :)

**Comment by avalentino** [comment]
@mraspaud 

> @avalentino Version 1.0.1 is released now. Can you confirm it works, and close the issue ?

uh sorry I missed this message
Yes, I confirm it works

thank you
